export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function RegisterLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
        <html lang="en">
        <body style={{ margin: 0, padding: 0, minHeight: '100vh', backgroundColor: '#007FFF' }}>
          {children}
        </body>
      </html>
    )
  }
  